
export type SecretType = {
  name: string,

  JWT_SECRET: string,

  AUTH_TOKEN_SECRET: string,
  AUTH_TOKEN_EXPIRY: string,
  AUTH_REFRESH_TOKEN_EXPIRY: string,
  AUTH_REDIRECT_URI: string,

  GOOGLE_OAUTH_CLIENT_ID: string,
  GOOGLE_OAUTH_CLIENT_SECRET: string,
  GOOGLE_OAUTH_REDIRECT_URI: string,
  GOOGLE_OAUTH_SCOPE: string,
}

export const backendSecretEnv:SecretType = { 
  name : 'projectM',

  JWT_SECRET: 'JWT_SECRET',

  AUTH_TOKEN_SECRET: 'AUTH_TOKEN_SECRET',
  AUTH_TOKEN_EXPIRY: 'AUTH_TOKEN_EXPIRY',
  AUTH_REFRESH_TOKEN_EXPIRY: 'AUTH_REFRESH_TOKEN_EXPIRY',
  AUTH_REDIRECT_URI: 'AUTH_REDIRECT_URI',
  
  GOOGLE_OAUTH_CLIENT_ID: 'GOOGLE_OAUTH_CLIENT_ID',
  GOOGLE_OAUTH_CLIENT_SECRET: 'GOOGLE_OAUTH_CLIENT_SECRET',
  GOOGLE_OAUTH_REDIRECT_URI: 'GOOGLE_OAUTH_REDIRECT_URI',
  GOOGLE_OAUTH_SCOPE: 'GOOGLE_OAUTH_SCOPE',
};

